name: Update library

on:
  issues:
    types: opened

jobs:
  update_library:
    runs-on: macOS-latest
    name: Update library
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update library
        uses: ./
        with:
          GoogleToken: ${{ secrets.GoogleToken }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "Updated font library"
          git push
