on:
  issues:
    types: opened
    

jobs:
  update_library:
    runs-on: macOS-latest
    name: Update library
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Update library
        uses: ./
        env:
          GoogleToken: ${{ secrets.GoogleToken }}
